version: '3.7'

services:
  backend:
    container_name: acme-backend
    image: josesandovalp/do2122-latam
    ports:
      - '3000:3000'
    environment:
      - NAME=acme-explorer
      - PORT=3000
      - SERVER_TIMEOUT=20000
      - DB_URI=mongodb://mongo:27017/acme?retryWrites=true&w=majority
      - REDIS_URI=redis://redis:6379
      - GOOGLE_SERVICE_ACCOUNT=${GOOGLE_SERVICE_ACCOUNT}
    depends_on:
      - mongo
      - redis

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: explorer123
      MONGO_INITDB_DATABASE: acme-explorer

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '6379:6379'
