name: CI Frontend

on:
  push:
    paths:
      - 'frontend/react/**'
    branches:
      - main
  pull_request:
    paths:
      - 'frontend/react/**'
    branches:
      - main

env:
  GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

defaults:
  run:
    working-directory: frontend/react

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: ./frontend/react/package-lock.json

      - run: npm ci
      - run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: ./frontend/react/package-lock.json

      - run: npm ci
      - run: npm test

  test-e2e:
    name: Test E2E
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: ./frontend/react/package-lock.json

      - run: |
          touch .env
          echo NAME=acme-explorer >> .env
          echo PORT=3000 >> .env
          echo SERVER_TIMEOUT=20000 >> .env
          echo DB_URI=mongodb://admin:explorer123@mongo:27017/acme-explorer >> .env
          echo REDIS_URI=redis://redis:6379 >> .env
          echo SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} >> .env
          echo "GOOGLE_SERVICE_ACCOUNT=$GOOGLE_SERVICE_ACCOUNT" | tr '\n' ' ' >> .env
          cat .env
          mv .env ./../../backend
      - run: npm ci
      - run: docker-compose -f ./../../docker-compose.prd.yml up --build -d gateway
      - name: Cypress test
        run: npm run test:e2e
